version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql             # Для постоянного хранения данных
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Автозагрузка схемы из файла при первом запуске

volumes:
  mysql_data:
